#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other POSIX shell available, you can
#       try to invoke the script with that shell. Most Linux distributions
#       have a POSIX shell as /bin/sh.
#
#   (2) Runs this script from the directory where the build.gradle or settings.gradle is.
#
#   (3) This script uses /dev/null as a file placeholder.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    link=$(expr "$PRG" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(dirname "$PRG")"/$link"
    fi
done
SAVED="$(cd "$(dirname "$PRG")" >/dev/null 2>&1 && pwd)"
cd "$SAVED" || exit 1
APP_HOME=$(expr "$SAVED" : '\(.*\)/gradle')

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

save () {
    for i ; do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #
  CYGWIN* )         cygwin=true  ;; #
  Darwin* )         darwin=true  ;; #
  MSYS* | MINGW* )  msys=true    ;; #
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to \"$JAVA_HOME\" but \"$JAVACMD\" does not exist!" >&2
    fi
else
    JAVACMD="$( which java )" || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" && ! "$nonstop" ; then
    case $MAX_FD in #
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #
      '' | soft) :;; #
      *)
        # In POSIX sh, ulimit -n is undefined. It will print a'ulimit: -n: invalid option' if used.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D options to set system properties
#   * plus a few other small options
# the terse mode switch, used to have leading '-'.
if [ "$GRADLE_OPTS" = "" ] ; then
    GRADLE_OPTS="$DEFAULT_JVM_OPTS"
else
    GRADLE_OPTS="$DEFAULT_JVM_OPTS $GRADLE_OPTS"
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --windows "$JAVACMD" )

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=$( find -L / -maxdepth 3 -type d -name .git -o -type d -name .svn 2>/dev/null | head -5 )
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGWIN_ARGS" != "" ] ; then
        ROOTDIRSRAW="$ROOTDIRSRAW $GRADLE_CYGWIN_ARGS"
    fi
    # Now convert the arguments - kinder to read 'case' statement than appending multiple shifts
    i=0
    for arg in "$@" ; do
        CHECK=$( echo "$arg"|egrep -c '^-' ) ### Determine if an option

        if [ $CHECK -eq 1 ] ; then    ### Added a condition
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        eval "KW_$i"=\"$arg\"
        i=$((i+1))
    done
fi

if [ "$OSTYPE" = "cygwin" ] ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --windows "$JAVACMD" )
fi

# Escaping properties is necessary to make backpath work.
APP_ARGS=$( save "$@" )

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#   * shell script including quotes and variable substitutions, so put them in
#   * double quotes to make sure that they get re-expanded; and
#   * put the whole thing in single quotes so that *everything* is protected from
#   * parameter expansion, command substitution and arithmetic expansion
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" has processed all taken arguments; the remaining ones
# are submitted to Gradle as-is with --stacktrace to have in depth
# diagnostics below too if they should fail.
remainder=()
while :
do
    case "$1" in
      *)
        remainder+=( "$1" )
        shift
        ;;
    esac
    [ ${#remainder[@]} -eq 0 ] && break
done

exec "$JAVACMD" "${JVM_OPTS[@]}" -Dorg.gradle.appname="$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "${remainder[@]}"
